### ISSUE TITLE
Wishlist: Saltillo for Mazatec, Aztecan and Mayan languages

### ISSUE THREAD

**Issue by fitojb** [CatharsisFonts/EauDeGaramond#4]
Several languages spoken across Mexico and Guatemala use the _[saltillo](https://en.wikipedia.org/wiki/Saltillo_(linguistics))_ (representing [ʔ] or [h]) in their orthographies. It’d be awesome if you could add these oft-neglected characters to your typeface :)

U+A78B Ꞌ
U+A78C ꞌ

**Comment by CatharsisFonts** [comment]
Hi Adolfo, 

I gave it a try in Eau and in Cormorant. Do they look right? I can't tell...

Cheers!

**Comment by fitojb** [comment]
Christian, thank you for your consideration and quick response! As a fan of your fonts, I appreciate it a lot. :)

Hm, spacing-wise, your saltillos seem to work just fine. I just have a question w.r.t. the height of U+A78B, which is more elevated than the cap height line, instead of being aligned to it. See this screenshot for a comparison with Times. In the end of the line I put an ASCII apostrophe (U+0027), both saltillos and an exclamation mark (the capital saltillo is sometimes described as a dotless exclamation mark, although it’s slightly thinner).

Feel free to ignore my height concern, as I just typeset books but can’t design type :)

![captura de pantalla de 2017-04-07 09-11-31](https://cloud.githubusercontent.com/assets/554953/24804139/133796ca-1b73-11e7-892d-adcafecde222.png)

**Comment by CatharsisFonts** [comment]
The font I checked for reference all had capital saltillos extending above the cap height. I'm happy to take it down if that's preferable. 

Cheers

**Comment by CatharsisFonts** [comment]
Like this, then?
<img width="431" alt="screen shot 2017-04-07 at 16 51 50" src="https://cloud.githubusercontent.com/assets/13754106/24805576/8d5f3cf2-1bb2-11e7-904a-26642fd3d368.png">
I hope I'm not saying anything naughty here...!   ;o)

**Comment by fitojb** [comment]
Nah, it’s just the endonym of the Tlapanec people and language ;)

Thanks a lot, now it looks much more “standard”. I guess I asked you to do this because it’s a frequent thing here to set titles in all-caps and fit that into strictly-square lines, which can be achieved with a cap saltillo that aligns to the other caps.

Anyway, again, thank you a lot for taking the time to do this!
