### ISSUE TITLE
half rings and percent sign

### ISSUE THREAD

**Issue by mewtant** [CatharsisFonts/EauDeGaramond#6]
The modifier left and right half rings are more or less deformed in the regular, extra-light, light, semi-light, and medium weights.  In the italics of these weights, the percent sign is also defective.  (I haven’t checked the infant fonts).

Thanks for making fonts with modifier half rings; they’re essential in my work!

**Comment by CatharsisFonts** [comment]
Thanks! Should be fixed in the new commit.

**Comment by mewtant** [comment]
Thanks for the quick repair!  That takes care of the percent sign and of the half rings in the upright fonts, but the half rings in the italic fonts are still distorted.

**Comment by CatharsisFonts** [comment]
D'oh, sorry! Fixed. I also noticed the half-rings were badly aligned in the Italic. Does that work now?
BTW, are they _supposed_ to be so small...?

**Comment by mewtant** [comment]
Perfect!  Yes, the half rings look right to me.  They could be very slightly bigger and still look good, but the chief thing is that they’re not too small to be readable, and they do look like half rings, not like apostrophes or a superscript c.
